### PR TITLE
Function for adding initial guess on Js added.

### PR DESCRIPTION
**Pull request by Stardaniele**
This will be useful i think

### CODE REVIEW

**Comment by nmovshov** [comment]
@Stardaniele 
What is a typical way of using this? Are you thinking of setting a guess of the "physical" Js? Because yes we may have an idea of what a few exterior Js might be. But the function as written requires us to specify a guess for the structure `obj.Js` with all its fields. To work correctly the input argument `Js_0` must be a struct  with fields
```
Js_0.tilde
Js_0.tilde_prime
Js_0.pprime
Js_0.tpprime
```
Is this convenient? If yes we can make a `set.Js()` method (Basically similar to your function but instead calling a function the user can just say `cms.Js = Js_0` which is slightly nicer.) But what is the typical case where you would want to use this?

p.s. the other change from this branch (allowing contrbution function to show mass) I will include in master now. Good idea!

**Comment by Stardaniele** [comment]
@nmovshov 
Usually what i do is:
cmp(ic).cms.set_Js_guess(cmp(ic-1).cms.Js);
So that I get the full structure for cms.Js from the previous iteration. If you update only the physical Jn, it won't help the convergence since you also need the gravitational field inside the planet to be close as the new solution, and not only the exterior field.
We can also make a set.Js() method, but I did it as a separate method because you don't want really to change the Js values if not for setting the initial guess on them. Anyway, I don't see major drawback in doing so. It's your choice.

**Comment by nmovshov** [comment]
Ok I understand now! Well I think this means it is finally time to implement what c++ calls a "copy constructor." Basically what you would *like* to say is something like
```
cmp(ic) = cmp(ic -1);
```
to start a next iteration. Right? Except right now you can't do that because cmp is a "handle class" so all you get is a new handle (matlab pointer) to the same actual object. Maybe this is fine for some things but sometimes you want a new object, started with the values copied from an old one. I think MATLAB has an easy way to do this, I'll check right now.

Or do you think it is still important to have a method to copy _just_ the `Js` struct and not other things?

**Comment by Stardaniele** [comment]
What I do now is to create a new CMP object, also because you need to change a lot of basic information, like tra spacing (you want to move transition and core location), or the EOSs with new values of K and/or n. I think is easier to just create a whole new CMP object, without duplicating the old one and change just what you need. The time-consuming part is the relax_to_barotrope() method, which I suppose will not have any advantages.
It may be useful when we want to change just a the density structure, and EOSs nor transitions are there, but in that case maybe we can simply use the same model, update the density and relax again, saving only the quantities we need (the densities).

**Comment by nmovshov** [comment]
okay I agree. For the case if speeding up convergence it is probably more useful to start with a guess for `zetas` actually! I think I will implement both options. but it will probably be more important to do
```
cmp(ic).cms.zetas = cmp(ic-1).cms.zetas;
```

**Comment by Stardaniele** [comment]
I've tried also updating the zetas but, don't ask me why, I saw that there was a speed increment only by updating the Js and NOT also updating the zetas. Pretty strange. But maybe a method to update them would be also useful to test more if in some other case it will improve the convergence.
Also, the first step you do when relaxing is actually update the zetas, which may be the reason why they do not bring much advantages (even if the equation to update the zetas uses the zetas itself!).

**Comment by nmovshov** [comment]
Pulled in the change manually to master branch.

**Pull request closed without merging**
